### ISSUE TITLE
Is there anyway to get notified about the actual state of the alarm

### ISSUE THREAD

**Issue by rossdargan** [nickandrew/LS30#11]
I know that I can call arm.pl and see whats going on but ideally what I want to do is have some code execute any time the alarm state changes (away/disarm etc)

The events just doesn't have enough information.

I'm guessing if it could be done it would have been :)

**Comment by nickandrew** [comment]
From what I can gather (looking through my logs), it's possible to capture a Disarm command from a remote control via both device event and ContactID message. An Arm or Home command will be reported via a device event.

So if you only arm/disarm the alarm system through a remote control then yes, you can process an appropriate event with a watch script.

Otherwise, and in the more general case, you'll have to poll the device for 'Operation Mode' - see bin/get-mode.pl for example.

**Comment by rossdargan** [comment]
Thats what I thought :) Thanks!
